//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBGO.Framework.MyModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blogs()
        {
            this.Catalogs = new HashSet<Catalogs>();
        }
    
        public int ID { get; set; }
        public string NiName { get; set; }
        public string Identity { get; set; }
        public string Title { get; set; }
        public string Signal { get; set; }
        public string Discription { get; set; }
        public int UserID { get; set; }
        public string LOGO { get; set; }
        public int ThemeID { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime EditTime { get; set; }
        public bool Status { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalogs> Catalogs { get; set; }
    }
}
