//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBGO.Framework.MyModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog()
        {
            this.Article = new HashSet<Article>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int BlogID { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime EditTime { get; set; }
        public bool Status { get; set; }
        public int ArticleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Article { get; set; }
        public virtual Blog Blog { get; set; }
    }
}
