//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBGO.Framework.MyModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int ID { get; set; }
        public string Contents { get; set; }
        public int ArticleID { get; set; }
        public string ArticleTitle { get; set; }
        public int Form_UserID { get; set; }
        public System.DateTime AddTime { get; set; }
        public int To_UserID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
