//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBGO.Framework.MyModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebCatalog
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public string Name { get; set; }
        public int Refleshs { get; set; }
        public int Total { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime EditTime { get; set; }
        public bool Status { get; set; }
        public Nullable<int> Admin_ID { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
